- menu_name: "Services"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "RSS"
  url: "/feed.xml"
  title: "RSSを購読"

- name: "Atom"
  url: "/atom.xml"
  title: "Atomを購読"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
